--Render Sitelen Pona text. One file per glyph.
local love = love
local sp = {}

local info = love.filesystem.getInfo( "sitelenpona" )
for _, filename in ipairs(love.filesystem.getDirectoryItems( "sitelenpona" )) do
  sp[filename:gsub( ".png", "" )] = love.graphics.newImage( "sitelenpona/"..filename )
end
--Render one glyph in the center.
sp.Draw = function( str )
  local w, h = love.graphics.getDimensions()
  local x, y = 0.5 * w - 128, 0.5 * h - 128
  love.graphics.setColor( 1.0, 1.0, 1.0, 0.5 )
  love.graphics.draw( sp[str] or sp.q, x, y )
end


return sp